### ISSUE TITLE
User Story: Find a Bed

### ISSUE THREAD

**Issue by keithboone** [AudaciousInquiry/fhir-saner#23]
Scenario: Find a Bed

As a [Treating Provider](../wiki/Persona#treating-provider), [Emergency Responder](../wiki/Persona#emergency-responder) or [Public Health Official](../wiki/Persona#public-health-official) I want to find a bed (Acute/Inpatient/ED) bed for patient treatment
so that I can route a patient to an appropriate treatment location.

Given a patient at {Location}
and {LocationFilter} criteria
When I look at {TreatmentLocation} on a map filtered by {LocationFilter}
Then I can see one or more {Facility}'s with {AvailableBeds} meeting the  {LocationFilter} requirements
and I can contact {Facility}

**Comment by narupley** [comment]
Can someone explain how these user stories fit into the SANER connectathon track? I thought we were going to be supporting the search interaction on the MeasureReport resource. What's all this about "Group" resources and supporting search on those? What does that have to do with the track?

Or are these user stories meant to be extra things outside the scope of the connectathon?

**Comment by keithboone** [comment]
Group is old, MeasureReport is where we are now, the story doesn't change, the technical implementation does and would support MeasureReport.

**Comment by narupley** [comment]
Okay, does that mean that most of the search URL examples given above are no longer valid then? Looking at the official MeasureReport specification there are only these search parameters supported:
- date
- evaluated-resource
- identifier
- measure
- patient
- period
- reporter
- status
- subject
I don't see any "type", "code", or "value" search parameters in the MeasureReport spec: https://www.hl7.org/fhir/measurereport.html

**Comment by JohnMoehrke** [comment]
Keith was telling us that there was a SearchParameter defined for code in MeasureReport.. but I don't see it in the artifact list.  Do we need it if we can search on measure?

**Comment by awatson1978** [comment]
> Also real-talk: how well is `near` supported at all? Testing in HAPI we can see https://covid19-under-fhir.smilecdr.com/baseR4/Location?_id=Loc-Org-7313 exists and has a position of:
> 
> ```
>       "position": {
>         "longitude": -66.857596987,
>         "latitude": 18.031300765
>       }
> ```
> 
> but [https://covid19-under-fhir.smilecdr.com/baseR4/Location?_id=Loc-Org-7313&near=-66.85|18.03|5000|km](https://covid19-under-fhir.smilecdr.com/baseR4/Location?_id=Loc-Org-7313&near=-66.85%7C18.03%7C5000%7Ckm) doesn't find it.

Symptomatic now officially supports the`near` search query.  

![Screen Shot 2020-05-31 at 1 05 27 AM](https://user-images.githubusercontent.com/675910/83346932-9ee1d700-a2e6-11ea-9f17-7c54bdbe3fc5.png)

This is long overdue, since Meteor Development Group added the `$near` operator to minimongo over 5 years ago.  But suffice it to say that we've been working with $near operators on the server, database AND client.  That is, we can support that URL search query syntax on our server router, where it searches the Mongo geospatial index like a typical database; but the client page router can also intercept the url query, and handle the `near` search on just the local client data.  So it's all isomorphic, and designed for distributed algorithms.

**Comment by awatson1978** [comment]
Also, querying by `_id=Loc-Org-7313 ` on the `near` search is redundant, since the centroid is contained within `near=-66.85|18.03|5000|km`
